name: Build and Publish Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Fetch Submodules Recursively
      run: git submodule update --init --recursive

    - name: Generate project
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\generate.bat

#    - name: Build iw8-mod
#      working-directory: ${{env.GITHUB_WORKSPACE}}
#      run: msbuild /m /p:Configuration=Release .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: iw8-mod
#        path: build/iw8_vs2019/x64/client/discord_game_sdk.dll
        path: generate.bat

#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: latest
#        release_name: iw8-mod ${{ github.sha }}
#        body: iw8-mod ${{ github.sha }} - released from GitHub Actions
#        draft: false
#        prerelease: false

    - name: Create Release and Upload DLL
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: iw8-mod ${{ github.sha }}
        make_latest: true
#        files: build/iw8_vs2019/x64/client/discord_game_sdk.dll
        files: generate.bat
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
