name: Build and Publish Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Fetch Submodules Recursively
      run: git submodule update --init --recursive

    - name: Generate project
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\generate.bat

    - name: Build iw8-mod
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: iw8-mod
        path: build/iw8_vs2019/x64/client/XInput9_1_0.dll
